name: driving_license
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  fluentui_icons: ^1.0.0
  flutter_svg: ^2.0.10+1
  firebase_core: ^2.28.0
  youtube_player_flutter: ^9.0.0
  simple_circular_progress_bar: ^1.0.2
  flutter_otp_text_field: ^1.1.2+1
  firebase_auth: ^4.19.0
  firebase_messaging: ^14.8.0
  flutter_dotenv: ^5.1.0
  

dev_dependencies: 
  flutter_lints: 3.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
  - assets/


