// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4k-3Q1icp6OLKmQhzFTeIRWPi2ZO5Yyo',
    appId: '1:695393802145:web:ce68c0a03024eb4a139de0',
    messagingSenderId: '695393802145',
    projectId: 'driving-licence-325f7',
    authDomain: 'driving-licence-325f7.firebaseapp.com',
    storageBucket: 'driving-licence-325f7.appspot.com',
    measurementId: 'G-TN4C5TT45B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByyy8CWeJbS5rJ3gF_ICpJ8lG3bg5r7f4',
    appId: '1:695393802145:android:e1d1c629833dbf6d139de0',
    messagingSenderId: '695393802145',
    projectId: 'driving-licence-325f7',
    storageBucket: 'driving-licence-325f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5oeLqQif6F0EdQqN3U_1PriGdj4WOvy0',
    appId: '1:695393802145:ios:a7cd12c1d2783191139de0',
    messagingSenderId: '695393802145',
    projectId: 'driving-licence-325f7',
    storageBucket: 'driving-licence-325f7.appspot.com',
    iosBundleId: 'com.pixelpoint.drivingLicense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5oeLqQif6F0EdQqN3U_1PriGdj4WOvy0',
    appId: '1:695393802145:ios:61a6a18e691fbcf1139de0',
    messagingSenderId: '695393802145',
    projectId: 'driving-licence-325f7',
    storageBucket: 'driving-licence-325f7.appspot.com',
    iosBundleId: 'com.pixelpoint.drivingLicense.RunnerTests',
  );
}
